# PyTorch Basic

PyTorch 기초 사용법

In [1]:
import numpy as np

import torch

In [2]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
nums.shape

torch.Size([9])

In [4]:
type(nums)

torch.Tensor

In [5]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [6]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
randoms = torch.rand((3,3))
randoms

tensor([[0.2950, 0.6246, 0.4019],
        [0.3956, 0.8053, 0.8208],
        [0.3244, 0.8594, 0.4256]])

In [8]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
zeros.size()

torch.Size([3, 3])

# Operations

PyTorch로 수학연산

In [12]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [13]:
nums = nums.reshape((3,3))
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [14]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [15]:
torch.add(nums, 3)

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [16]:
result = torch.add(nums,10)

In [17]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

## View

In [18]:
range_nums = torch.arange(9).reshape(3,3)

In [19]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Slice and Index

In [22]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [23]:
nums[1]

tensor([3, 4, 5])

In [24]:
nums[1,1]

tensor(4)

In [25]:
nums[1:,1:]

tensor([[4, 5],
        [7, 8]])

In [26]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [27]:
arr = np.array([1,1,1])
arr

array([1, 1, 1])

In [28]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 1, 1], dtype=torch.int32)

In [29]:
arr_torch.float()

tensor([1., 1., 1.])

In [30]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [31]:
arr_torch.to(device)

tensor([1, 1, 1], dtype=torch.int32)

# AutoGrad
- 기울기를 주는 것이다
- 학습이 되게 만드는 것

In [32]:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [33]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [34]:
print(y.grad_fn)

In [35]:
z = y * y * 3
out = z.mean()

In [36]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [37]:
out.backward()

In [39]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [42]:
print(x.requires_grad) # 기울기를 구하는 것

True


In [41]:
print((x **2).requires_grad)

True


In [46]:
with torch.no_grad(): # 기울기나 계산을 안해서 더 빨라진다
    print((x**2).requires_grad) # test 할때는 no_gard를 사용해서 하면 된다

False
